language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6.0
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=1.4.10
    - python: "3.3"
      env: DJANGO=1.4.10
# command to install dependencies
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py install
# command to run tests
script: python setup.py test
